### ISSUE TITLE
Publish to jcenter as well.

### ISSUE THREAD

**Issue by emanuelez** [KeepSafe/ReLinker#14]
Right now, if a library project uses ReLinker, it needs to tell its users to add the jitpack repository, which is inconvenient.

Publishing to jcenter would solve the issue as it's the standard repository for Android projects.

**Comment by xiphirx** [comment]
jcenter is now the default, 53248a2da84670e764648f6f701c78c58a235f16
jitpack can still be used if desired.

Please confirm your jcenter dependency is resolving successfully. If not, please open another issue.
