### ISSUE TITLE
Logger does not get the actual exception thrown 

### ISSUE THREAD

**Issue by xiphirx** [KeepSafe/ReLinker#16]
Makes it hard to debug exactly _what_ is wrong. The library should report at least the exception message to the logger.

**Comment by TheChuckster** [comment]
I'm sure you've thought of this already, but please be sure to use custom ReLinker.log() com.getkeepsafe.relinker.ReLinker.Logger interface implementations if they are available.

Speaking for myself, I'll need these propagated up to my own custom remote logger so I can see users' logs remotely.

**Comment by TheChuckster** [comment]
^ Looks like you already took care  of that! Nice!
