### ISSUE TITLE
Relinker.loadLibrary(final Context context, final String library, final String version)

### ISSUE THREAD

**Issue by dshen6** [KeepSafe/ReLinker#18]
To specify a library version, you have to obtain a ReLinkerInstance via ReLinker.log()/ ReLinker.recursively()/ReLinker.force(). Does this seem a little arbitrary? What if I want none of those things, but do want to load with a version? I'm doing ReLinker.log(null).loadLibrary(...) in the meantime.

Keep up the good work!

**Comment by xiphirx** [comment]
Thanks for the report! This is an oversight in the API :) Will fix soon (or if you'd like to submit a PR that would be greatly appreciated as well)

**Comment by xiphirx** [comment]
6c9bcda31127bd85b34786d1106e8fe4402aae14 Please use `1.2.1`

**Comment by dshen6** [comment]
Thanks!
