### ISSUE TITLE
UnsatisfiedLinkError issue

### ISSUE THREAD

**Issue by onexuan** [KeepSafe/ReLinker#22]
I use relinker lib, but it catch UnsatisfiedLinkError issue

Model:K-Touch W619
Manufacturer:unknown
Version:10
Release Version:2.3.6
ProductName:msm7627a
CPU:armeabi-v7a
java.lang.UnsatisfiedLinkError: Cannot load library: load_library[1104]: Library /data/data/com.xxxxxx/app_lib/libxxxx.so not found

**Comment by xiphirx** [comment]
Hi, are you distributing your APK with ABI splits enabled?

**Comment by onexuan** [comment]
this lib work well. I fix many UnsatisfiedLinkError issues in some rom. but I got this UnsatisfiedLinkError issue yesterday, using android-ndk-r12 to build all platform, include 64 bit.

This is my code

static {
		try {
			System.loadLibrary("xxxx");
		} catch (UnsatisfiedLinkError e) {
			if (YiApplication.app != null) {
				ReLinker.loadLibrary(YiApplication.app, "xxxx",
						new ReLinker.LoadListener() {
							@Override
							public void success() {
							}

							@Override
							public void failure(Throwable t) {
								try {
									CrashHandler.getInstance().writeLog(t, true);
								} catch (Exception e) {

								}
							}
						});
			}
		}
	}

**Comment by xiphirx** [comment]
Glad to hear it is fixing many issues. Do you have ABI splits enabled?

**Comment by onexuan** [comment]
I don't know what is "ABI splits enabled"?

**Comment by onexuan** [comment]
I know "ABI splits enabled" now, My app is not ABI splits

**Comment by xiphirx** [comment]
Can you check the available internal storage free space on the device? That particular device only has 512 MB of internal memory. I suspect it is running out of space.

**Comment by onexuan** [comment]
Device is not mine. this issue is uploaded to my log service. so I can't know internal memory, Maybe this /data/data/com.xxxxxx/app_lib folder is not created (app_lib is not created), or app_lib is created but it is a file, not a folder, I met this situation

this is my old code
```
                              File folderFile = new File(context.getFilesDir()
						.getParentFile(), libFolder);
				File libFile = new File(folderFile, "libxxxx.so");

				if (!folderFile.isDirectory()) {
					folderFile.delete();
					folderFile.mkdirs();
				} else if (!folderFile.exists())
					folderFile.mkdirs();
```

**Comment by xiphirx** [comment]
Yeah, unfortunately there isn't much information for me to go on... I suspect there is a storage space issue. You will inevitably get errors like this one, that's just a fact of life.

**Comment by onexuan** [comment]
I will add some code, if I encounter such a problem again, I will give you feedback! 
Relink works very well. I only caught this issue in K-Touch after I added your lib.  think you for your work!

**Comment by xiphirx** [comment]
I'm going to close this issue now, please open a new issue if you have more information. Thanks.
