### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "ibswresample.so" is 32-bit instead of 64-bit

### ISSUE THREAD

**Issue by elyonsaber** [KeepSafe/ReLinker#25]
Hi, I am now using ReLinker to relink .so files in my project like this
` ReLinker.log(logger).recursively().loadLibrary(context, "avcodec");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavcodec");
        ReLinker.log(logger).recursively().loadLibrary(context, "avdevice");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavdevice");
        ReLinker.log(logger).recursively().loadLibrary(context, "avfilter");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavfilter");
        ReLinker.log(logger).recursively().loadLibrary(context, "avformat");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavformat");
        ReLinker.log(logger).recursively().loadLibrary(context, "avutil");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniavutil");
        ReLinker.log(logger).recursively().loadLibrary(context, "postproc");
        ReLinker.log(logger).recursively().loadLibrary(context, "jnipostproc");
        ReLinker.log(logger).recursively().loadLibrary(context, "swresample");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniswresample");
        ReLinker.log(logger).recursively().loadLibrary(context, "swscale");
        ReLinker.log(logger).recursively().loadLibrary(context, "jniswscale");`
In some devices, it works well. However in some device like  MI Note Pro (5.1.1) and HuaWei TIT-AL00 (5.1), it reports error as:
![huawei](https://cloud.githubusercontent.com/assets/15250710/17172309/08e2aa8e-5427-11e6-8b39-0eb5a8ff2d11.png) 
CPU info of MI Note:
![minotecpu](https://cloud.githubusercontent.com/assets/15250710/17172327/24fc68a4-5427-11e6-8f4e-7add8955328e.jpg)
CPU info of HuaWei:
![huaweicpu](https://cloud.githubusercontent.com/assets/15250710/17172372/64aceeba-5427-11e6-9dd2-6ce791362b61.png)
So what should I do to resolve this issue? Thanks!

**Comment by xiphirx** [comment]
Are you mixing 32 bit and 64 bit libraries? If any of your libraries are built for 64 bit architectures then you need a 64 bit version of each other library. You also could only include 32 bit versions of your libraries and that will work as well.

This is not an issue with ReLinker, it is how the system works. Either include 64 bit versions for all libraries or only use 32 bit versions.

**Comment by elyonsaber** [comment]
Great thanks! I checked all dependencies in my project, and it's because of [Fresco](https://github.com/facebook/fresco). It has library built for 64 bit architecture, and then brings error like [this](https://github.com/facebook/fresco/issues/361).
