### ISSUE TITLE
Can't use ReLinker with Android SDK 17

### ISSUE THREAD

**Issue by dantheman20051** [KeepSafe/ReLinker#28]
My app uses Android SDK 17.
In SystemLibraryLoader.java, the following line can't be compiled
if (Build.VERSION.SDK_INT >= 21 && Build.SUPPORTED_ABIS.length > 0) 
due to SUPPORTED_ABIS not being found.
Is it safe to just uncomment this:
/*  if (Build.VERSION.SDK_INT >= 21 && Build.SUPPORTED_ABIS.length > 0) 
        {
            return Build.SUPPORTED_ABIS;
        } 
        else  */
or will this cause problems on some devices? Have tested on my own Android 6.0 device and it worked.

**Comment by xiphirx** [comment]
Your project configuration is not ideal. You shouldn't be compiling against such an old SDK. Rather, set your mininum sdk version to 17 and compile with the latest sdk. This is not an issue with the library, but rather your configuration.

The code block you ask about is not something that should be commented out. For devices on API >= 21, you will miss architectures that the device can support.
