### ISSUE TITLE
Update path

### ISSUE THREAD

**Issue by janseeger** [KeepSafe/ReLinker#3]
Hi first of all, thanks for releasing ReLinker!

Pleaes correct me if I am wrong here: I noticed there's no way to update the app once ReLinker has been applied.

In [#71](https://github.com/KeepSafe/ReLinker/blob/master/library/src/main/java/com/getkeepsafe/relinker/ReLinker.java#L71) it only checks whether the workaroundLib file exists but not if the Version matches, (e.g. after the App was updated and the native interface may have changed).

In snipped linked in your article the Chromium folks seem to have worked around this by unpacking the library once on every app start.

**Comment by xiphirx** [comment]
Hi there,

You can update your app with ReLinker, you just need to take care of versioning yourself. It is true that ReLinker will not extract the same library name twice, so the easiest way to setup some sort of versioning system is to append a version number to the library name.

In general, I feel that versioning is outside the scope of this project.

**Comment by xiphirx** [comment]
@janseeger Hi there. I've gone ahead and added versioning support with #11
