### ISSUE TITLE
can I use relinker for import static library?

### ISSUE THREAD

**Issue by michalisKolozoff** [KeepSafe/ReLinker#31]
I just want to ask something. In my project I do not use System.loadlibrary. But I use import static <library>
and it crashes with an unsatisfiedlinkerror exception can I use relinker in this case?

**Comment by benjamin-bader** [comment]
Static libraries aren't linked at runtime, so no - you'd have to incorporate it into your JNI build.

**Comment by xiphirx** [comment]
Can you provide sample code for how you're loading your library? I'm unsure what "import static" means in this context.

**Comment by libathos** [comment]
I am sorry what I meant, was that at the beginning of my class where I add all my imports I use:

`import static com.googlecode.javacv.cpp.opencv_core.IPL_DEPTH_8U;`

and sometimes in my code when I want to call a certain function I use:

`com.googlecode.javacv.cpp.opencv_contrib.createLBPHFaceRecognizer(1,8,8,8,100);`

**Comment by xiphirx** [comment]
You need to call `ReLinker.loadLibrary(...)` before any native function can be called.  This is typically done in the static initializer of the class that provides the native methods. If you're unable to modify the class that provides the native methods, then it would probably be advantageous to create a wrapper class.
