### ISSUE TITLE
How to build relinker for ant?

### ISSUE THREAD

**Issue by rcdailey** [KeepSafe/ReLinker#39]
I'm not using Gradle yet for our android project (for various reasons outside of my control). I'd like to use relinker with my android project.

What I figured I'd do is use gradle to build a `jar` file and just put that in my `libs` directory so it gets pulled in and I can use it.

I'm not having any luck building relinker though. I modified `relinker/build.gradle` to set these differently:

```
    compileSdkVersion 15
    buildToolsVersion "26"
```

After that it fails:

```
$ gradle

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':relinker'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 0s
```

I am using a version of gradle I downloaded directly from the gradle website. I do not use Android Studio at the moment. Not sure what the issue is, hopefully you can help.

Thanks in advance.

**Comment by benjamin-bader** [comment]
You need the Android SDK installed to build ReLinker, and the easiest way to do that today is to download Android Studio.  Use that to build your jar, and you'll be good to go.

Alternately, you could go get the jar from mvnrepository.com or something.

**Comment by rcdailey** [comment]
I do have the SDK installed, and my ANDROID_SDK environment variable points to it.

**Comment by benjamin-bader** [comment]
Then I'm not sure how to help you, unfortunately - the error message is meaningless to me.  I'd recommend just downloading the pre-built AAR from mvnrepository, personally, then overriding the constants in your android manifest.

If you really need to make the build yourself, I'd suggest googling the error message, or hitting up stackoverflow.

**Comment by benjamin-bader** [comment]
One thing that occurs to me - usually I wouldn't run `gradle` directly.  I'd use the wrapper script, which takes care of procuring the correct binary.  From the repo root, try `./gradlew build`; maybe that will help.

**Comment by ajalt** [comment]
I don't think there's anything else we can do on this issue. If you need an aar, you can download it from the maven repository.
