### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by sahana-tib** [KeepSafe/ReLinker#4]
When I put the compile 'com.github.KeepSafe:ReLinker:1.1' in my build.gradle it says Failed to resolve.
Please help

**Comment by xiphirx** [comment]
Hi, please make sure you have added Jitpack as a maven repository,

```
repositories { 
        jcenter()
        maven { url "https://jitpack.io" }
   }
```

in your gradle build file

**Comment by sahana-tib** [comment]
It did solve. Thankyou!!
