### ISSUE TITLE
Cannot load library: find_library, failed to load previously.

### ISSUE THREAD

**Issue by xiaos** [KeepSafe/ReLinker#41]
I got lot of this error in my app:

 Exception java.lang.UnsatisfiedLinkError: Cannot load library: find_library[1201]: 1681 '[REDACTED_DOMAIN_NAME]' failed to load previously
java.lang.Runtime.load (Runtime.java:340)
java.lang.System.load (System.java:521)
com.getkeepsafe.relinker.SystemLibraryLoader.loadPath (SystemLibraryLoader.java:29)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:198)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:92)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:189)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:92)

From here: https://github.com/KeepSafe/ReLinker/issues/15 I know that the developer solved it by compile the native libraries, but can we solve this in Relinker code?

**Comment by ajalt** [comment]
Unfortunately, this is due to a system configuration, so there's nothing we can do outside of the advice offered in the issue you lined. Sorry!
