### ISSUE TITLE
FR: support extractNativeLibs

### ISSUE THREAD

**Issue by alexcohn** [KeepSafe/ReLinker#56]
Does ReLinker support [android:extractNativeLibs=false](https://developer.android.com/reference/android/R.attr.html#extractNativeLibs) ?

There are few *levels* of such support. 

- For starters, you can detect android:minSdkVersion and recommend to use uncompressed libraries
- You can also disable the ReLinker if this flag is set
- Finally, you could backport this feature to versions of Android below 24.

**Comment by p2kyc0ng** [comment]
ReLinker current version support “android:extractNativeLibs=false”
