### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by koral--** [KeepSafe/ReLinker#60]
If ReLinker is published to Maven Central then other libraries published there may depend on it.

**Comment by venator85** [comment]
Publishing on Maven Central is now crucial, since Jcenter is scheduled to be dismissed on May 1st, 2021.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by emarc-m** [comment]
Relinker v1.4.3 is now available in MavenCentral: https://repo1.maven.org/maven2/com/getkeepsafe/relinker/relinker/.
