### ISSUE TITLE
Please clarify in documentation, whether ReLinker is only useful for certain API levels

### ISSUE THREAD

**Issue by marcardar** [KeepSafe/ReLinker#64]
In more recent versions of Android (since 23) we have extractNativeLibs option in the application element of the Android Manifest file. Is ReLinker still beneficial when setting this flag to false?

Also, what specific issues (maybe point to some issues in the Android issuetracker) are solved by this library?

**Comment by chrisjenx** [comment]
We were just wondering this, is this still needed on newer devices. (We are 21+)

**Comment by bendb-instacart** [comment]
It's not 100% clear that the package-manager bugs were fixed as of 21, but for 23+ I believe ReLinker is no longer necessary.

@chrisjenx the only real way to know for your case would be to ship without relinked, and just watch for UnsatisfiedLinkErrors.  Or, to be safe, just use it and remember to tear it out when you bump your min SDK to 23.

**Comment by benjamin-bader** [comment]
It's not 100% clear that the package-manager bugs were fixed as of 21, but for 23+ I believe ReLinker is no longer necessary.

@chrisjenx the only real way to know for your case would be to ship without relinked, and just watch for UnsatisfiedLinkErrors. Or, to be safe, just use it and remember to tear it out when you bump your min SDK to 23.

**Comment by hborders** [comment]
Consider updating the javadoc in `ReLinker.java` to mention this.
