### ISSUE TITLE
Is ReLinker still required after API 21?

### ISSUE THREAD

**Issue by hborders** [KeepSafe/ReLinker#71]
The `ReLinker.java` javadoc says:
> ReLinker is a small library to help alleviate `UnsatisfiedLinkError` exceptions thrown due to Android's inability to properly install / load native libraries for Android versions before API 21

But I can't find any official documentation on the Relinker blog [1][2] or in the readme saying the last Android version where Relinker is still required. Could you please add some documentation about this?

**Comment by benjamin-bader** [comment]
See #64.  The tl;dr is that we don't actually _know_ at which API level relinker is no longer needed.  To find out would require either a) learning way more about AOSP or b) removing relinker and seeing who crashed.  Neither of those seems likely to happen any time soon.

Rumor has it that it's safe to load libraries without relinker as of API 23, but I'd strongly advise you to verify that for yourself.

**Comment by DanAlbert** [comment]
The library search order issues were fixed with JB MR2 (API 18) iirc. The issue remains for `NativeActivity` until API 24 I believe, but ReLinker can't help there anyway.

I don't remember when the installer issues were fixed, but API 23 is roughly the right era.

@enh-google might remember better.

**Comment by enh-google** [comment]
> The library search order issues were fixed with JB MR2 (API 18) iirc.

correct. see https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#changes-to-library-dependency-resolution for details (where we ever suggest that anyone hit by this should use ReLinker :-) ).

> The issue remains for `NativeActivity` until API 24 I believe, but ReLinker can't help there anyway.
> 
> I don't remember when the installer issues were fixed, but API 23 is roughly the right era.
> 
> @enh-google might remember better.

sadly not, and -- whenever it was -- it was long enough ago that i couldn't find the bug. but, yeah, that feels like the right era. iirc the package manager folks thought they'd fixed it in 21 (and did at least _improve_ things there), but there were some lingering issues for a while longer.

**Comment by benjamin-bader** [comment]
Thanks for the authoritative answers!  I'll open a documentation PR and just call it at API 24 to be safe.
