### ISSUE TITLE
Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so

### ISSUE THREAD

**Issue by Gitjiatao** [KeepSafe/ReLinker#75]
E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service io.rong.imlib.ipc.RongService@495a5e1 with Intent { cmp=com.xiniu.manmoli/io.rong.imlib.ipc.RongService (has extras) }: io.rong.imlib.relinker.MissingLibraryException: libdl.so
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3304)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1638)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:165)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6375)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.b.a(SourceFile:38)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.d(SourceFile:15)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:8)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.d(SourceFile:21)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:8)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at sd.f.a(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at io.rong.imlib.NativeObject.<init>(SourceFile:3)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at gd.Yd.a(SourceFile:19)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at gd.hc.<init>(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at io.rong.imlib.ipc.RongService.onBind(SourceFile:4)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3290)
08-07 01:58:34.841  7763  7763 E AndroidRuntime: 	... 8 more

**Comment by benjamin-bader** [comment]
It looks like you're repackaging relinker and obfuscating your app, which means that it's quite difficult to get useful information from this stacktrace.  Can you post one that's not obfuscated please?  Also, are you able to verify that your APK does in fact contain `libdl.so` in the architecture expected?

**Comment by Gitjiatao** [comment]
My apk doesn't contain libdl.so. This is belong to system.But for unknown reasons, it also reminder MissingLibraryException: libdl.so.

**Comment by Gitjiatao** [comment]
My apk doesn't contain libdl.so. This is belong to system.But for unknown reasons, it also reminder MissingLibraryException: libdl.so.

**Comment by Gitjiatao** [comment]
My apk doesn't contain libdl.so. This is belong to system.But for unknown reasons, it also reminder MissingLibraryException: libdl.so.

**Comment by Gitjiatao** [comment]
My apk doesn't contain libdl.so. This is belong to system.But for unknown reasons, it also reminder MissingLibraryException: libdl.so.

**Comment by Gitjiatao** [comment]
My apk doesn't contain libdl.so. This is belong to system.But for unknown reasons, it also reminder MissingLibraryException: libdl.so.

**Comment by benjamin-bader** [comment]
It's possible that the library you're intending to load depends on `libdl.so`.  Of course, you're correct, this is a system library and a fundamental one at that.

Does this crash 100% of the time, or only occasionally?  Do you notice any trends with these crashes?  Are they from a specific device, or a family of devices, or a single manufacturer?  Do they all declare the same ABI?  What OS versions do you see exhibiting this crash?  The more info you can dig up, the better.

And it's still going to be very difficult to help you with only an obfuscated stacktrace.

**Comment by Gitjiatao** [comment]
only occasionally.
[case](https://github.com/rongcloud/rongcloud-im-flutter-sdk/issues/120)
The Resources section shows a previous call stack.

**Comment by benjamin-bader** [comment]
I must apologize, for I cannot read any of the linked issue.  I do note that the stack trace there is _also_ obfuscated.  I would like to help you but obfuscation and the language barrier are preventing me.  Please add any information that you think might help here; otherwise, I'm not going to be able to offer any useful advice.

**Comment by Gitjiatao** [comment]
Thank you for your help.  Call stack as follow.
Manufacturer: Xiaomi and Huawei.

--------- beginning of crash
06-06 00:02:57.105  6945  6945 E AndroidRuntime: FATAL EXCEPTION: main
06-06 00:02:57.105  6945  6945 E AndroidRuntime: Process: com.manmolly.merchant:ipc, PID: 6945
06-06 00:02:57.105  6945  6945 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service io.rong.imlib.ipc.RongService@a8d337 with Intent { cmp=com.manmolly.merchant/io.rong.imlib.ipc.RongService (has extras) }: io.rong.imlib.relinker.MissingLibraryException: libdl.so
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3281)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1629)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6337)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.b.a(SourceFile:38)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.d(SourceFile:15)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:8)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.d(SourceFile:21)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:8)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at md.f.a(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at io.rong.imlib.NativeObject.<init>(SourceFile:3)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at ad.Yd.a(SourceFile:19)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at ad.hc.<init>(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at io.rong.imlib.ipc.RongService.onBind(SourceFile:4)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3267)
06-06 00:02:57.105  6945  6945 E AndroidRuntime: 	... 8 more
06-06 00:02:57.130  2469  2720 W JavaExceptionHandler: Too noisy! skip java exception report:com.manmolly.merchant:ipc now=1591372977129 mLastReportTime=1591372967562 interval=15000
06-06 00:02:57.152  2345  2391 I octvm_klo: klo lock
06-06 00:02:57.152  2526  2700 I WtProcessController: Receive am_crash event for pid: 6945 pkg = com.manmolly.merchant:ipc
06-06 00:02:57.152  2526  2700 W KloServer: Aborted broadcast does not supprt for: com.manmolly.merchant
06-06 00:02:57.164  2345  2391 I octvm_klo: get wanted event[mask:128, name:data_app_crash@1591372977159.txt] from the watchset
06-06 00:02:57.164  2345  2391 I octvm_klo: start gathering logcat log...
06-06 00:02:57.168  1508  1571 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@a2fa0e0
06-06 00:02:57.168  1508  1571 V BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@68bef99
06-06 00:02:57.183  2345  2391 I octvm_klo: gathering logcat log done
06-06 00:02:57.183  2345  2391 I octvm_klo: klo unlock
06-06 00:02:57.185   796  1604 I miuiFirewall: miui firewall always allow android
06-06 00:02:57.211  1508  6787 I Adreno  : QUALCOMM build                   : 4f3d4bc, I07a8b16b27
06-06 00:02:57.211  1508  6787 I Adreno  : Build Date                       : 10/26/17
06-06 00:02:57.211  1508  6787 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.04
06-06 00:02:57.211  1508  6787 I Adreno  : Local Branch                     : mybranch28842968
06-06 00:02:57.211  1508  6787 I Adreno  : Remote Branch                    : quic/gfx-adreno.lnx.1.0.r5-rel
06-06 00:02:57.211  1508  6787 I Adreno  : Remote Branch                    : NONE
06-06 00:02:57.211  1508  6787 I Adreno  : Reconstruct Branch               : NOTHING
06-06 00:02:57.224  1508  6787 I OpenGLRenderer: Initialized EGL, version 1.4
06-06 00:02:57.226  1508  6787 D OpenGLRenderer: Swap behavior 1
06-06 00:02:57.246  2062  2062 D wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'

**Comment by benjamin-bader** [comment]
This is the part that looks like it might possibly be useful, if it were deobfuscated:

> 06-06 00:02:57.105 6945 6945 E AndroidRuntime: Caused by: io.rong.imlib.relinker.MissingLibraryException: libdl.so
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.b.a(SourceFile:38)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.f.d(SourceFile:15)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.f.a(SourceFile:8)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.f.a(SourceFile:4)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.f.d(SourceFile:21)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.f.a(SourceFile:8)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at md.f.a(SourceFile:4)
06-06 00:02:57.105 6945 6945 E AndroidRuntime: at io.rong.imlib.NativeObject.(SourceFile:3)

The line numbers don't seem to match anything in relinker today.  What version are you using?

**Comment by Gitjiatao** [comment]
1.4.0
Not the latest version.

**Comment by benjamin-bader** [comment]
Thanks for the version number.  Look, I'm sorry, but I can't make any sense of this based on the info in this thread.  The line numbers don't match up to anything in version 1.4.0 of relinker; whatever repackaging, minification, and obfuscation is going on makes further assistance impossible.

I wish you luck in solving this issue.
