### ISSUE TITLE
JCenter to be shut down

### ISSUE THREAD

**Issue by tthiagomartinho** [KeepSafe/ReLinker#79]
Starting from May 1, 2021 [JCenter will stop working](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter). 
I was wondering if there are any plans to move to another repository, such as MavenCenter.

Thanks!

**Comment by barnhill** [comment]
Is this repo maintained any longer?  There hasnt been a commit or release in a year.

**Comment by benjamin-bader** [comment]
Relinker is maintained but is also basically feature-complete; there's not a lot of call for ongoing development.

**Comment by barnhill** [comment]
Awesome!!  We just need to get it published to MavenCentral I guess :)

**Comment by davidschreiber** [comment]
At PSPDFKit, we also [recommend customers to use ReLinker](https://pspdfkit.com/guides/android/current/miscellaneous/relinker/) when integrating our library into their apps. For that, our customers are relying on the public availability of the library. Since `jcenter()` was a default Maven provider for most Android projects, integration was simple and straight-forward. We would love to see a migration to `mavenCentral()` which is the second, universally accepted library that doesn't require any additional configuration in most Android projects.

The last update to this repository was about one year ago. Is the project really actively maintained?

**Comment by benjamin-bader** [comment]
> The last update to this repository was about one year ago. Is the project really actively maintained?

Depends on your definition of "actively".  As I said above, there really isn't much need for change in this project, so the commit log looks pretty sparse over the past few years.  This is the sign of a mature library whose dependencies also don't change much.

> We would love to see a migration to `mavenCentral()`

@philippb @emarc-m who is in charge of publishing stuff these days?  You'll want to address this soonish; jcenter will stop accepting updates in a month or two.

**Comment by emarc-m** [comment]
Hi everyone and @benjamin-bader, thank you for bringing this up to our attention. 

It's me and @tomasz-keepsafe who are handling the publishing of Android artifacts.

We'll get to it as soon as possible as you've recommended.

**Comment by tthiagomartinho** [comment]
> Hi everyone and @benjamin-bader, thank you for bringing this up to our attention. 
> 
> It's me and @tomasz-keepsafe who are handling the publishing of Android artifacts.
> 
> We'll get to it as soon as possible as you've recommended.

Thank you for taking care of it @emarc-m !

**Comment by barnhill** [comment]
Should we create a PR to this lib to handle this?

**Comment by emarc-m** [comment]
@barnhill I'd be happy to review a PR for integrating MavenCentral publishing to this project. 😄

**Comment by benjamin-bader** [comment]
The PR is only part the work; you'll have to get set up with a Sonatype account, publish a gpg signing key, and _then_ integrate those credentials with the code.  The code itself is pretty simple.  I'm happy to help walk you through the process if you need (and haven't done this already), Philipp can give you my contact info.

**Comment by barnhill** [comment]
I stuck a PR out there which I know wont work unless the credentials are put on the repo itself but it should be pretty straight forward.  Along with it there were some dependencies that were WAY out of date like the gradle plugin, and gradle itself.  Those are freebies.  Enjoy.  Ill be glad to have a look at any comments on the PR and make any corrections necessary to facilitate this moving forward.

**Comment by emarc-m** [comment]
Relinker v1.4.3 is now available in MavenCentral: https://repo1.maven.org/maven2/com/getkeepsafe/relinker/relinker/.

Thank you all for the help!
