### ISSUE TITLE
JCenter dependency

### ISSUE THREAD

**Issue by barnhill** [KeepSafe/ReLinker#86]
This library is still dependent on JCenter per 1 dependency.
The cause is due to using `gradlePluginPortal()` in the project build.gradle.  This was originally included as a fix for including `trove4j` but it appears that now this is available from mavenCentral.
https://search.maven.org/search?q=g:org.jetbrains.trove4j

**Comment by philippb** [comment]
@emarc-m Is this still an outstanding issue?

**Comment by emarc-m** [comment]
@philippb, yes. Thanks for the reminder.

I did not prioritize since JCenter decided to be read-only indefinitely: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/.

 I'll take care of this within the week to finally resolve this.

**Comment by emarc-m** [comment]
@barnhill Thanks again for the PR to address this.
I just published version `1.4.4` in MavenCentral.
