### ISSUE TITLE
Failed to resolve: com.getkeepsafe.relinker:relinker:1.4.1

### ISSUE THREAD

**Issue by Duna** [KeepSafe/ReLinker#90]
Failed to resolve: com.getkeepsafe.relinker:relinker:1.4.1

jcenter() - becomes obsolete in the new Arctic Fox

Please migrate to mavenCentral()

**Comment by benjamin-bader** [comment]
I believe we already did?  Try version 1.4.4.  I don't think we backfilled older releases.

**Comment by Duna** [comment]
Done, worked

**Comment by benjamin-bader** [comment]
Awesome, glad to hear it!

**Comment by cuichanghao** [comment]
the same problem
